id: dot-config-exposed
filter: true
level: 2
info:
  name: Dot Config Exposed
  risk: Potential
  confidence: Tentative

params:
  - root: "{{.BaseURL}}"

origin:
  method: GET
  redirect: false
  headers:
    - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
  url: >-
    {{.BaseURL}}/hopefully404.config

variables:
  - secret: File("~/wordlist/dot-config.txt")

requests:
  - method: GET
    redirect: false
    headers:
      - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3984.0 Safari/537.36
    url: >-
      {{.root}}/{{.secret}}
    detections:
      - >-
        Diff() && StatusCode() == 200 && !RegexSearch("response", "(?i)(Oops!|Whoops!|AutodiscoverService|not\sfound|Request\sRejected|Access\sDenied|a\sbad\sURL|has\sbeen\slocked)") && (RegexSearch("resHeaders", "Accept-Ranges.*bytes") || RegexSearch("resHeaders", ".*Content-Type:.*octet-stream") || RegexSearch("resHeaders", "text/plain")) && (Math.abs(ContentLength() - OriginContentLength()) > 200) && !RegexSearch("body", "(?i)(\<\!doctype|\<html|\<head|\<body||\<div)") && ContentLength('body') > 200  && !StringSearch("oresHeaders", "text/plain")